-- HoraFlow - importação inicial das demandas ABHO
-- Cliente ABHO: client_id = 3
-- Responsável: Otavio Cardena
-- Aprovado/Agosto -> execução 2026-08-01
-- Aprovado/Ínicio Agosto -> execução 2026-08-01
-- Aprovado/Setembro -> execução 2026-09-01
-- Aprovação sem mês -> execução NULL

START TRANSACTION;

INSERT INTO demands
(number, problem, treatment, analysis_hours, required_hours, priority,
 status, approval, paid, responsible, client_id, execution_month)
VALUES
(1, 'Cupons de Desconto — listagem com ordenação e filtros inadequados, dificultando a gestão dos registros.', 'Alterar ordenação padrão (ID decrescente), exibir por padrão apenas cupons ativos, adicionar filtro por status (Ativo/Inativo/Excluído logicamente/Todos), adicionar filtro de pesquisa por nome, ajustes e validações de consulta e interface.', 0.00, 6.00, 'Média', 'Não iniciado', 'Aprovado/Setembro', 0, 'Otavio Cardena', 3, '2026-09-01'),
(2, 'Ausência de ambiente de homologação, impedindo testes seguros antes da publicação em produção.', 'Configurar servidor VPS Hostinger KVM 4, aplicar hardening de segurança, configurar firewall, instalar serviços necessários, criar bancos de dados (Site ABHO e Chat ABHO), publicar ambientes de homologação (Site e Chat), configurar domínios/subdomínios e SSL, e realizar testes de acesso e funcionamento.', 0.00, 16.00, '**Alta**', 'Finalizado', 'Aprovado', 1, 'Otavio Cardena', 3, NULL),
(3, 'Reativação de Assinaturas — membro com pagamento cancelado ou assinatura cancelada não consegue realizar nova contratação (sistema retorna erro).', 'Analisar regras atuais de assinatura, ajustar o fluxo para permitir nova contratação após cancelamento, tratar assinaturas canceladas e pagamentos não concluídos, e realizar testes de regressão do fluxo.', 0.00, 8.00, '**Alta**', 'Finalizado', 'Aprovado', 1, 'Otavio Cardena', 3, NULL),
(4, 'Regeneração de Boletos — quando o boleto não é pago, o sistema não permite emissão de um novo, impedindo a continuidade da contratação.', 'Revisar a regra de geração de boletos, implementar mecanismo de emissão de novo boleto quando o anterior estiver vencido/cancelado/não pago, adicionar validações contra duplicidade de cobranças e realizar testes de homologação.', 0.00, 10.00, '**Alta**', 'Não iniciado', 'Pendente', 0, 'Otavio Cardena', 3, NULL),
(5, 'Exportação de Lista de Membros — campo de endereço exportado de forma unificada (endereço, número, cidade, estado e CEP no mesmo campo).', 'Ajustar a exportação CSV para separar os dados de endereço em colunas individuais (Endereço, Número, Cidade, Estado, CEP), mantendo nome, e-mail e assinatura, validando a estrutura do CSV e testando com endereços completos e incompletos.', 0.00, 4.00, 'Baixa', 'Não iniciado', 'Aprovado/Ínicio Agosto', 0, 'Otavio Cardena', 3, '2026-08-01'),
(6, 'Previsão de hr - inclusão de logo', 'Por favor, dar andamento na inclusão dos logos anexos em  <br>https\://abho.org.br/parceiros-2026/<br>https\://abho.org.br/cbhoebho-2026/<br>em CATEGORIA Apoio Institucional...<br>Direcionar para<br><br>fieramilano.com.br/<br>anest.org.br<br>acgih.org/<br>ioha.net/<br><br>Aplicados em ordem alfabética', 0.00, 1.00, 'Média', 'Finalizado', 'Aprovado', 1, 'Otavio Cardena', 3, NULL),
(7, 'Desconto por quantidade de produto', 'Identificamos que existe uma falha no painel atual: hoje ele exibe apenas os descontos por categoria de membro, mas não mostra os dois campos de desconto por quantidade, que seriam:<br><br>quantidade mínima para desconto e valor aplicado a partir dessa quantidade mínima.<br><br>Provavelmente esses metadados foram gravados por uma versão ou plugin anterior e permaneceram no banco após a migração para o tema atual, que ocorreu em algum momento.<br><br>Para corrigir, seria necessário reverter esse ponto adicionando novamente esses campos no painel administrativo, assim conseguimos ter controle para gerenciar e remover esses descontos quando necessário.', 0.00, 3.00, 'Alta', 'Finalizado', 'Aprovado', 1, 'Otavio Cardena', 3, NULL),
(8, 'Melhoria Chatbot', 'Não existe uma saudação padrão, então vamos configurar pra fixar essa.', 0.00, 2.00, 'Média', 'Não iniciado', 'Aprovado/Setembro', 0, 'Otavio Cardena', 3, '2026-09-01'),
(9, 'Alteração cadastro membro x compra site - Validar se o usuário pode conter multiplos endereço de entrega', 'Manter o endereço de correspondência bloqueado no cadastro do associado<br>Durante a compra, o endereço cadastral do membro não deve ser atualizado automaticamente.<br>Ou seja: uma compra não deve alterar os dados billing\_address\_1, billing\_number, billing\_neighborhood, billing\_city, billing\_state, billing\_postcode etc. do perfil do associado.<br>Criar/reativar uma seção própria para endereço de entrega<br>No checkout, deve existir uma opção do tipo:<br>“Enviar para outro endereço”<br>Quando marcada, o usuário informa um endereço separado de entrega, usando campos shipping\_\*.<br>Esse endereço deve valer apenas para o pedido atual, sem modificar o cadastro principal do associado.<br>Salvar o endereço de entrega no pedido, não no perfil do associado<br>O pedido deve guardar o endereço usado naquela compra, para logística/histórico.<br>Mas o perfil do membro deve permanecer com o endereço de correspondência original, salvo apenas quando ele editar explicitamente o cadastro.<br>Estimamos que para solucionar essa questão leve em torno de 4 horas. Pois faremos tratamento de regras e certificaremos que não ocorrerá a alteração de endereço e, ainda, salvará no pedido o novo endereço. Nessas horas já será contemplada tempo de teste do profissional de QA.', 0.00, 4.00, 'Média', 'Não iniciado', 'Aprovado/Agosto', 0, 'Otavio Cardena', 3, '2026-08-01'),
(10, 'Estimativa de Horas – Desenvolvimento da Tela de Programação<br>', 'Conforme alinhado, concluí o levantamento inicial da demanda juntamente com a Victoria. Ela ainda realizará alguns ajustes no protótipo, mas já conseguimos estimar o esforço necessário para esta atividade.<br><br>A estimativa ficou da seguinte forma:<br><br>1 hora para elaboração do protótipo/rascunho da tela;<br>4 horas para o desenvolvimento da tela.<br><br>Essa estimativa contempla tanto a construção do protótipo quanto o desenvolvimento da tela em programação.', 0.00, 5.00, 'Média', 'Finalizado', 'Aprovado', 1, 'Otavio Cardena', 3, NULL),
(11, 'Webhook WooCommerce —Status de Pagamento / Status retornados pelo WooCommerce via webhook não são tratados corretamente.', 'Revisar todos os webhooks configurados, mapear eventos de pagamento e implementar atualização automática de status.', 0.00, 5.00, 'Alta', 'Não iniciado', 'Pendente', 0, 'Otavio Cardena', 3, NULL),
(12, 'Cancelamento de Assinatura —Pedido em Aguardando', 'Automatizar a sincronização de status entre assinatura cancelada e pedido correspondente no WooCommerce. Quando executa assinatura para ser membro e não efetua o pagamento, o status fica em aguardando, e ao cancelar a assinatura o status do pedido segue em "Aguardando" impossibilitando uma nova geração de filiação.', 0.00, 6.00, 'Alta', 'Não iniciado', 'Aprovado/Agosto', 0, 'Otavio Cardena', 3, '2026-08-01'),
(13, 'Aprovação sem Anuidade -- É possível aprovar membros sem pagamento da anuidade via tela de edição.', 'Implementar validação obrigatória de pagamento antes de permitir aprovação de membros, bloqueando o fluxo sem confirmação financeira.', 0.00, 4.00, 'Média', 'Não iniciado', 'Aprovado/Setembro', 0, 'Otavio Cardena', 3, '2026-09-01'),
(14, 'Link CBHO & EBHO 2026', '[Diminuir o tamanho do link abho.org.br/programacao-preliminar-cbho-ebho-2026/, para https://abho.org.br/progamacao-2026/.](http://abho.org.br/programacao-preliminar-cbho-ebho-2026/)', 0.00, 1.00, 'Alta', 'Finalizado', 'Aprovado', 1, 'Otavio Cardena', 3, NULL),
(15, 'Campanha WhatsApp', 'Para viabilizar o envio da campanha via WhatsApp, será necessário realizar a configuração da plataforma Meta Business. Para essa etapa, está previsto um prazo de até 48 horas.', 0.00, 48.00, 'Alta', 'Finalizado', 'Aprovado', 1, 'Otavio Cardena', 3, NULL),
(16, 'Usuário não consegue efetuar o pagamento', 'O PagBank limita payment\_method.boleto.holder.name a 30 caracteres para boleto, segundo a documentação oficial do objeto Order. Esse pedido estava enviando:<br>SESI SERVICO SOCIAL DA INDUSTRIA = 32 caracteres<br>Por isso o PagBank recusava a criação da cobrança, mas o plugin trocava o erro real por "There was an error during the payment.".<br>Ajustamos para cortar esse campo para 30 caracteres via filtro pagbank\_boleto\_payment\_data. Validei o payload e agora ele envia: SESI SERVICO SOCIAL DA INDUSTR = 30 caracteres', 0.00, 3.00, 'Alta', 'Finalizado', 'Aprovado', 1, 'Otavio Cardena', 3, NULL),
(17, 'Alterado validação de email de plugin para PHP', 'Não estava sendo enviado email de verificação de email', 0.00, 1.00, 'Alta', 'Finalizado', 'Aprovado', 1, 'Otavio Cardena', 3, NULL),
(18, 'Livro toxicologia \*ATUALIZADO', 'Foi inserido o livro diretamente via Código', 0.00, 2.00, 'Alta', 'Finalizado', 'Aprovado', 1, 'Otavio Cardena', 3, NULL),
(19, 'Alteração palestrantes, textos e redirecionamento pagina de programação preliminar', 'Feito ajustes de imagens e textos de palestrantes, alterado redirecionamento e implementado moderados e palestras', 0.00, 1.00, 'Média', 'Finalizado', 'Aprovado', 1, 'Otavio Cardena', 3, NULL),
(20, 'Ajuste página CBHO&EBHO 2026', '- Remover Painéis confirmados<br>- Ajustar nomenclatura de Painéis para Programação e redirecionar para Programação Preliminar<br>- Adicionar Eventos apoiados', 0.00, 1.00, 'Alta', 'Finalizado', 'Aprovado', 1, 'Otavio Cardena', 3, NULL),
(21, 'Ao ir para checkout implementar a opção padrão para inserir frete', 'Atualmente, usuários sem endereço cadastrado têm a opção "Retirada no Local" selecionada automaticamente. A alteração será solicitar apenas o CEP ao acessar o checkout (removendo os campos País, Estado e Bairro). Após informar o CEP, o usuário deverá completar o endereço antes de finalizar a compra.', 0.00, 2.00, 'Média', 'Não iniciado', 'Pendente', 0, 'Otavio Cardena', 3, NULL),
(22, 'Alterar Saudação do Wpp pelo Chat bot', 'Alterar mensagem de saudação enviada para evitar mensagem de audio e imagens via whatsApp', 0.00, 1.00, 'Média', 'Finalizado', 'Aprovado', 1, 'Otavio Cardena', 3, NULL),
(23, 'Adicionar modal para leitura de Livro', 'Atualmente a leitura do livro está exibindo a baixo dos livros existentes', 0.00, 1.00, 'Média', 'Finalizado', 'Aprovado', 1, 'Otavio Cardena', 3, NULL),
(24, 'Consolidação de Usuários Duplicados', 'Adicionar regras e validações de usuários principais para unificar e excluir duplicidades e inibir novas ocorrências.', 2.50, 24.00, 'Alto', 'Não Iniciado', 'Pendente', 0, 'Otavio Cardena', 3, NULL),
(25, 'Medidas de Segurança de Arquivos', 'Arquivos estão expostos para todas as pessoas em Revistas, Livros, Imagens de Usuários e Certificados. PDFs de livros e revistas estão exposta em pesquisas do google. Levantado esforço e PDF Enviado', 0.00, 22.00, 'Crítico', 'Não Iniciado', 'Pendente', 0, 'Otavio Cardena', 3, NULL),
(25, 'Adicionar botões novo botão de redirecionamento para cursos onlines e presenciais', 'Atualmente contem cursos que são presenciais que podem ser feito on-line, para esses cursos conterá um novo botão redirecionando para o curso on-line. E para os cursos que são on-lines terá o redirecionamento para o curso presencial', 0.00, 2.00, 'Média', 'Finalizado', 'Aprovado', 1, 'Otavio Cardena', 3, NULL),
(26, 'Fazer correçõe Pontuais - Solicitado por Raquel', 'Ajustar Imagem de Produto, Ajustar texto de desconto + pacotes de cursos. Alterar imagem de livro.', 0.00, 1.00, 'Média', 'Finalizado', 'Aprovado', 1, 'Otavio Cardena', 3, NULL),
(27, 'Adicionar novo checkout de retirada para produto especifico', 'Atualmente não existe cadastro de frete para produtos. Foi necessario implementar via codigo e registrar a forma de entrega para compra', 0.00, 2.00, 'Alta', 'Finalizado', 'Aprovado', 1, 'Otavio Cardena', 3, NULL),
(28, 'Ajustar textos, imagens e moderadores de programação pre-liminar, e adição de parceiro em APOIO INSTITUCIONAL', 'Inserido corpo de texto da apresentação de Lucas Diniz, Inserida imagem de palestrantes, e aidicionado apresentadores na Composição da mesa. E adicionado novo Parceiro institucional APMT', 0.00, 1.00, 'Média', 'Finalizado', 'Aprovado', 0, 'Otavio Cardena', 3, NULL),
(29, 'Ajuste de validação de estoque na pagina de [https://abho.org.br/cbhoebho-2026/](https://abho.org.br/cbhoebho-2026/)', 'Mesmo após colocar que estava fora do estoque, o produto ainda exibia em uma pagina, na qual nao fazia validação se estava fora de estoque. Foi inserida essa validação.', 0.00, 1.00, 'Média', 'Finalizado', 'Aprovado', 0, 'Otavio Cardena', 3, NULL),
(30, 'Revista 83. Prever a inclusão da Revista anexa com o acesso exclusivo para membros. <br> <br>', 'Incluir a Revista somente para membros,  somente para leitura, sem possibilidade de download.', 0.00, 1.00, 'Média', 'Não Iniciado', 'Pendente', 0, 'Otavio Cardena', 3, NULL);

COMMIT;
